version: '3.4'
services:
  postgres:
      container_name: postgres
      image: postgres:latest
      environment:
        POSTGRES_DB: "bookstoredb"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "123"
      volumes:
        - postgres-data:/var/lib/pgsql/data
      ports:
        - "5432:5432"
volumes:
  postgres-data: